name: Test-Build

on:
  push:
  pull_request:

jobs:
  linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    container:
      image: swift:6.2-noble

    steps:
      - uses: actions/checkout@v4
      # - uses: beeauvin/swiftly-swift@v1
        # with:
          # swift-version: 6.1
      - name: Install Swiftly & Swift 6.2.0
        uses: vapor/swiftly-action@v0.2
        with:
          toolchain: 6.2.0
      - name: Build
        working-directory: Swiftified-CLI
        run: |
          swift --version
          swift build -Xswiftc -static-stdlib
      - name: Debug
        working-directory: Swiftified-CLI
        run: |
          cd .build
          cd x86_64-unknown-linux-gnu
          cd debug
          ls
          echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: Linux-${{ env.BUILD_ID }}
          path: ${{ GITHUB.WORKSPACE }}/Swiftified-CLI/.build/x86_64-unknown-linux-gnu/debug/Swiftified

  maccli:
    name: Build CLI (macOS)
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Swiftly & Swift 6.2.0
        uses: vapor/swiftly-action@v0.2
        with:
          toolchain: 6.2.0
      - name: Build
        run: |
          cd ${{ GITHUB.WORKSPACE }}/Swiftified-CLI
          swift build --arch arm64 --arch x86_64
          echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: macOS CLI-${{ env.BUILD_ID }}
          path: ${{ GITHUB.WORKSPACE }}/Swiftified-CLI/.build/apple/Products/Debug/Swiftified
